# Generated by Django 5.2.4 on 2025-08-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_sitesetting_site_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='sitesetting.sitesetting')),
            ],
        ),
    ]
